apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "18"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"backstage","namespace":"backstage"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"backstage"}},"template":{"metadata":{"labels":{"app":"backstage","commit-hash":"12f3de8"}},"spec":{"containers":[{"envFrom":[{"secretRef":{"name":"postgres-secrets"}},{"secretRef":{"name":"backstage-secrets"}}],"image":"reyshazni/backstage-app:12f3de8","imagePullPolicy":"IfNotPresent","name":"backstage","ports":[{"containerPort":7007,"name":"http"}]}]}}}}
    creationTimestamp: "2024-07-26T03:09:21Z"
    generation: 18
    name: backstage
    namespace: backstage
    resourceVersion: "11294729"
    uid: 3389c5cc-3edb-424d-b692-8523f6e1298d
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: backstage
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2024-08-14T10:29:07+07:00"
        creationTimestamp: null
        labels:
          app: backstage
          commit-hash: 12f3de8
      spec:
        containers:
        - envFrom:
          - secretRef:
              name: postgres-secrets
          - secretRef:
              name: backstage-secrets
          image: reyshazni/backstage-app:12f3de8
          imagePullPolicy: IfNotPresent
          name: backstage
          ports:
          - containerPort: 7007
            name: http
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2024-08-09T13:26:45Z"
      lastUpdateTime: "2024-08-09T13:26:45Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2024-07-31T06:13:24Z"
      lastUpdateTime: "2024-08-26T08:23:53Z"
      message: ReplicaSet "backstage-574f8d687" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 18
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
