# kubernetes/backstage-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
data:
  GITHUB_TOKEN: Z2hwX3dsYWlOOWhCNXROZmVBRHFmdmRES3M0MDBvdUV6QjRKUEVIQQo=
---
apiVersion: v1
data:
  GITHUB_TOKEN: Z2hwX3dsYWlOOWhCNXROZmVBRHFmdmRES3M0MDBvdUV6QjRKUEVIQQo=
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
---
apiVersion: v1
data:
  POSTGRES_PASSWORD: YmFja3N0YWdl
  POSTGRES_USER: YmFja3N0YWdl
kind: Secret
metadata:
  name: postgres-secrets
  namespace: backstage
type: Opaque