name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
    types: [closed]

env:
  PROJECT_NAME: ${{ github.event.repository.name }}
  PORT: 7007

  GCP_REGION: asia-southeast2
  GCP_ZONE: asia-southeast2-a

  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: intern-sandbox

jobs:
  setup-environment:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.set-env.outputs.IMAGE_TAG }}
      IMAGE_NAME: ${{ steps.set-env.outputs.IMAGE_NAME }}
      SHORT_SHA: ${{ steps.set-env.outputs.SHORT_SHA }}
    steps:
      - name: Set environment variables
        id: set-env
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          IMAGE_NAME="reyshazni/${{ github.event.repository.name }}:$SHORT_SHA"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_OUTPUT
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT

  dockerize-and-push:
    needs: setup-environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Login Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create config
        run: |
          echo "${{ vars.APP_CONFIG }}" > ./app-config.yaml
          echo "${{ vars.APP_CONFIG_PRODUCTION }}" > ./app-config.production.yaml

      - name: Create secrets
        run: |
          cd packages/backend
          mkdir secrets
          cd secrets
          echo '${{ vars.GCP_SA_KEY }}' > ./gcp_sa.json
          echo '${{ vars.GCP_SA_KEY_TEST }}' > ./gcp_sa_test.json

      - name: Build and push Docker Image
        env: 
          IMAGE_NAME: ${{ needs.setup-environment.outputs.IMAGE_NAME }}
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT

  deploy-to-server-eks:
    needs: [setup-environment, dockerize-and-push]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Prepare deployment file
        env: 
          IMAGE_NAME: ${{ needs.setup-environment.outputs.IMAGE_NAME }}
          SHORT_SHA: ${{ needs.setup-environment.outputs.SHORT_SHA }}
        run: |
          sed -i "s|<IMAGE_NAME>|${{ env.IMAGE_NAME }}|g" k8s/service/2-app.yml
          sed -i "s|<VERSION>|${{ env.SHORT_SHA }}|g" k8s/service/2-app.yml
          sed -i "s|<PORT>|${{ env.PORT }}|g" k8s/service/2-app.yml
          cat k8s/service/2-app.yml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Deploy
        run: |
          kubectl apply -f k8s/service/2-app.yml --validate=false